### ISSUE TITLE
ERROR:platform_thread_win.cc(127)] NOT IMPLEMENTED

### ISSUE THREAD

**Issue by sitoto** [easonhan007/lazyman#5]
OS： win7
ruby：ruby 1.9.3p125 (2012-02-16) [i386-mingw32]
chrome：chromedriver_win32_2.3.zip  ChromeDriver server for win32 (v2.3.220795) supports Chrome v28-31
lazyman (0.1.13)

C:\Sites\pei>lazyman c
         run  bin/console from "."
Starting ChromeDriver (v2.3) on port 9515
[5072:2844:0925/101709:ERROR:platform_thread_win.cc(127)] NOT IMPLEMENTED

> > [4548:4644:0925/101714:ERROR:textfield.h(173)] NOT IMPLEMENTED

**Comment by easonhan007** [comment]
this error message is from chrome driver not lazyman, if you do not want to see this again ,please use ff instead.
